version: "3.7"
services:
  postgresql:
    container_name: partizer-db
    image: postgres:13.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=partizer
      - POSTGRES_USER=partizer
      - POSTGRES_PASSWORD=partizer_dev_pass
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    networks:
      - db
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER}"]
      timeout: 5s
      retries: 3

networks:
  db:
    external: false